# Generated by Django 4.2.3 on 2023-07-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_titel_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create',
        ),
        migrations.RemoveField(
            model_name='post',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='uploded_at',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=250),
        ),
    ]
