# Generated by Django 4.2.3 on 2023-07-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prof_image',
            field=models.ImageField(null=True, upload_to='images/profile'),
        ),
    ]
